# Generated by Django 5.0.1 on 2024-02-06 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=9)),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('dateTime', models.TimeField()),
                ('archived', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('photo', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('bed', models.CharField(max_length=255)),
                ('amenities', models.JSONField()),
                ('description', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('orderDate', models.DateField()),
                ('orderTime', models.TimeField()),
                ('checkinDate', models.DateField()),
                ('checkinTime', models.TimeField()),
                ('checkoutDate', models.DateField()),
                ('checkoutTime', models.TimeField()),
                ('notes', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelMiranda.rooms')),
            ],
        ),
    ]
