# Generated by Django 5.0.1 on 2024-02-09 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelMiranda', '0002_booking_email_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkinTime',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkoutTime',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='orderDate',
            field=models.DateField(default=datetime.date(2024, 2, 9)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='orderTime',
            field=models.TimeField(default=datetime.time(11, 37, 24, 687279)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=129),
        ),
        migrations.AlterField(
            model_name='booking',
            name='photo',
            field=models.CharField(default='https://castillotrans.eu/wp-content/uploads/2019/06/77461806-icono-de-usuario-hombre-hombre-avatar-avatar-pictograma-pictograma-vector-ilustraci%C3%B3n.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='booked', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 9)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='dateTime',
            field=models.TimeField(default=datetime.time(11, 37, 24, 687279)),
        ),
    ]
