# Generated by Django 5.0.1 on 2024-02-09 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_booking_email_booking_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='orderTime',
            field=models.TimeField(default=datetime.time(12, 29, 9, 421494)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='dateTime',
            field=models.TimeField(default=datetime.time(12, 29, 9, 420493)),
        ),
    ]
