# Generated by Django 5.0.1 on 2024-02-09 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_booking_ordertime_alter_contact_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='orderTime',
            field=models.TimeField(default=datetime.time(12, 31, 8, 835445)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='dateTime',
            field=models.TimeField(default=datetime.time(12, 31, 8, 835445)),
        ),
    ]
