# Generated by Django 5.0.1 on 2024-02-12 11:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_booking_ordertime_alter_contact_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='orderDate',
            field=models.DateField(default=datetime.date(2024, 2, 12)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='orderTime',
            field=models.TimeField(default=datetime.time(12, 28, 41, 130381)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 12)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='dateTime',
            field=models.TimeField(default=datetime.time(12, 28, 41, 130381)),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('food', 'food'), ('other', 'other')], max_length=10)),
                ('description', models.TextField()),
                ('timestamps', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
