name: Deployment HotelMiranda Django

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: connect to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd dashboard-django
            
            git pull origin main
            /home/ubuntu/dashboard-django/env/bin/pip install -r requirements.txt
            /home/ubuntu/dashboard-django/env/bin/python3 hotelMiranda/manage.py makemigrations
            /home/ubuntu/dashboard-django/env/bin/python3 hotelMiranda/manage.py migrate
            sudo systemctl restart nginx
            sudo systemctl restart gunicorn
            sudo /home/ubuntu/dashboard-django/env/bin/python3 manage.py collectstatic